Repository ELVIS-SOFTWARE/elvis, pull requests merged in 2024-05, with the labels that each got.

#44 ELVIS-1139-Inscription-message-erreur
  app/models/user.rb
  frontend/components/activityApplications/UserSearch.js
Labels: enhancement

#45 Wizard, add new first step on user not selected
  app/controllers/activities_applications_controller.rb
  app/controllers/planning_controller.rb
  app/controllers/users_controller.rb
  app/mailers/liquid_drops/json_drop.rb
  app/models/user.rb
  app/services/time_intervals/availabilities_utils.rb
  config/routes.rb
  frontend/components/activityApplications/TimePreferencesStep.js
  frontend/components/activityApplications/Wizard.js
  frontend/components/activityApplications/WizardUserSelectMember.js
  frontend/components/availability/AvailabilityManager.js
  frontend/packs/application.scss
Labels: new feature

#41 ZIGGY-885--Wizard-Coordonnées
  frontend/components/common/AlertCheckbox.js
  frontend/components/common/AlertYesNoRadio.js
  frontend/components/common/Input.js
  frontend/components/common/InputSelect.js
  frontend/components/userForm/ConsentDocItem.js
  frontend/components/userForm/ContactInfos.js
  frontend/components/userForm/Fields.js
  frontend/components/userForm/GeneralInfos.js
  frontend/components/userForm/HandicapInfos.js
  frontend/components/userForm/SelectSameAs.js
  frontend/components/userForm/UserForm.js
  frontend/tools/obj.js
Labels: enhancement

#40 ELVIS-1131--Affichage-durée
  frontend/components/activityApplications/ActivityChoice.js
  frontend/components/activityApplications/summary/Activity.js
Labels: enhancement

#38 ELVIS--1109-Créneau-edit-modal
  app/controllers/activity_instance_controller.rb
  app/services/activities/conflicts_checker.rb
  app/services/activities/time_interval_updater.rb
  frontend/components/activityApplications/ActivityChoice.js
  frontend/components/planning/ActivityDetailsModal.js
  frontend/components/planning/Planning.js
Labels: bug

#46 ELVIS-1141-Mes-Demandes-d'inscription
  app/controllers/users_controller.rb
  app/models/user.rb
  frontend/components/PreApplication.js
  frontend/components/UserAvatar.js
  frontend/components/activityItems/AnswerProposal.js
  frontend/components/activityItems/CancelApplication.js
  frontend/components/activityItems/CurrentActivityItem.js
  frontend/components/activityItems/EditApplication.js
  frontend/components/activityItems/NewActivityItem.js
  frontend/components/activityItems/RenewActivityItem.js
  frontend/components/activityItems/renderActivityAction.js
Labels: enhancement

#48 ZIGGY-891--Wizard-3-parameter
  app/controllers/activities_applications_controller.rb
  app/controllers/parameters/activity_application_parameters_controller.rb
  app/views/activities_applications/new.html.erb
  app/views/activities_applications/new_for_existing_user.html.erb
  config/routes.rb
  frontend/components/activityApplications/ActivityChoice.js
  frontend/components/activityApplications/Wizard.js
  frontend/components/parameters/ActivityApplications/ActivityApplicationsParameters.js
  frontend/components/parameters/ActivityApplications/ApplicationStepParameters.js
Labels: enhancement

#47 ZIGGY-886-Wizard-Résumé
  app/controllers/users_controller.rb
  app/services/users/search_user.rb
  frontend/components/activityApplications/EvaluationChoiceTable.js
  frontend/components/activityApplications/SelectedActivitiesTable.js
  frontend/components/activityApplications/TimePreferencesTable.js
  frontend/components/activityApplications/Validation.js
  frontend/components/activityApplications/Wizard.js
Labels: enhancement

#49 ELVIS-1146--Wizard-3-cosmetics
  frontend/components/activityApplications/ActivityChoice.js
Labels: enhancement

#50 ELVIS-1144--Inscription-1-design
  frontend/components/UserAvatar.js
  frontend/components/activityApplications/WizardUserSelectMember.js
Labels: enhancement
